### ISSUE TITLE
Allow server member in Discord to chat without verifying/linking when account link is required

### ISSUE THREAD

**Issue by syaraf-az** [Riku32/DiscordLink#14]
**Describe the feature**
Allow non-verified/non-linked member to chat with Minecraft player in crosschat channel even with `link.required` is set to `true`.

**Description**
Currently, the plugin when configured to require account linkage, anyone who want to crosschat with MC players also need to be verified, meaning that everyone need to have Minecraft account and do linking process once to chat even though if they didn't want to play in the first place.

The setup that I tried to do is, if someone want to play in the server, they need to link the MC with Discord account but anyone else are free to talk in the channel to talk with MC players. But, the plugins enforce the need to be linked first before they can chat.

**Comment by JSH32** [comment]
It seems a little bit weird to both require linking which means that it would not allow the player to play until they verify AND allow them to talk. This doesn't seem like a particularly useful feature/option so could you explain why this may be useful?
