### ISSUE TITLE
If possible make a version using the fabric api pls (fabric is used mainly in the private smp servers)

### ISSUE THREAD

**Issue by crazyaccess** [Riku32/DiscordLink#4]

**Comment by JSH32** [comment]
Rn its spigot. I have plans to make it a platform agnostic api which will function on many implementations including fabric

**Comment by JSH32** [comment]
I have decided for now this is a bit of an out-of-scope request. This plugin just started so I'm not going to focus on making it platform-independent. BUT I do definitely plan on it when the plugin is established. For now, you could use [Cardboard](https://cardboardpowered.org/) with 1.16 or 1.17 (1.17 is coming soon). This will let you use this plugin on a Fabric server.
