### ISSUE TITLE
Player gets killed in end (fallen to void), or teleports to spawn in overworld when the "allow only linked" mode is on

### ISSUE THREAD

**Issue by crazyaccess** [Riku32/DiscordLink#5]
**Describe the bug**
When you implement the mod for the first time and set the "only linked" mode on then players in end and in the overworld gets tp'ed at void and spawn respectively once they link themselves successfully in the /link protocol, 

**To Reproduce**
1. Get a fresh paper install
2. Goto end
3. Install the DiscordLink by RIku Sama mod and then reload.
4. Config the yaml file, and set the "linked only mode" mode to on
5. now login to the server
6. now link your profile

**Expected behavior**
Nothing the player should be able to continue what they were doing (didn't check for nether or if the player_entity is flying or something)

**Screenshots**
... dun have any ...

**Additional context**
maybe add like a lobby for non linked players (like how 2b2t does in their server (some void lobby) ),
So that it will be helpful even in Offline mode servers and help prevent others getting to know what locations the user is in if someone trys to login with their id (i am a online mode user, but i used to use offline mod back in the days when no mone)

**Comment by crazyaccess** [comment]
Enhancement
 : Additionally add the discord channel description thingy (which updates once in a while giving statistics about the server)

**Comment by crazyaccess** [comment]
Either i will pr with some edits on : https://github.com/Riku32/DiscordLink/blob/master/src/main/java/com/github/riku32/discordlink/events/PlayerActivity.java

or 

https://github.com/Riku32/DiscordLink/blob/master/src/main/java/com/github/riku32/discordlink/discord/listeners/VerificationListener.java

or atleast i can hint where it is being casued

**Comment by JSH32** [comment]
Yeah I know why, it sends them to the current world spawn after verification. I can probably send them to the main overworld spawn or hook into essentially. Honestly not sure, you got any suggestions? I can't do 2b2t lobby since that's leaning to the bungee side of things. And yeah its the join method on VerifyListener

**Comment by JSH32** [comment]
> Enhancement
>  : Additionally add the discord channel description thingy (which updates once in a while giving statistics about the server)

Id suggest making a feature request for this one. It seems like something servers would want so I might implement it

**Comment by crazyaccess** [comment]
> Yeah I know why, it sends them to the current world spawn after verification. I can probably send them to the main overworld spawn or hook into essentially. Honestly not sure, you got any suggestions? I can't do 2b2t lobby since that's leaning to the bungee side of things. And yeah its the join method on PlayerActivity

Like make them more like resume where they did the link thingy

**Comment by crazyaccess** [comment]
Also riku sama pls provide your discord or send me a friend req on : crazyaccess#7707

(i might wanna ask something questionable)

**Comment by JSH32** [comment]
> > Yeah I know why, it sends them to the current world spawn after verification. I can probably send them to the main overworld spawn or hook into essentially. Honestly not sure, you got any suggestions? I can't do 2b2t lobby since that's leaning to the bungee side of things. And yeah its the join method on PlayerActivity
> 
> Like make them more like resume where they did the link thingy

Yeah I was doing this originally I was just thinking that people would want a location for people verifying but yeah that makes more sense in the end. Atm in about to board a plane but I'll fix it asap when im back

**Comment by JSH32** [comment]
> Also riku sama pls provide your discord or send me a friend req on : crazyaccess#7707
> 
> (i might wanna ask something questionable)

Sent i guess lmao

**Comment by crazyaccess** [comment]
Well oke thanks or maybe i can help with that too i will push a pr soon 


LoL : Riku sama is rich

> > > Yeah I know why, it sends them to the current world spawn after verification. I can probably send them to the main overworld spawn or hook into essentially. Honestly not sure, you got any suggestions? I can't do 2b2t lobby since that's leaning to the bungee side of things. And yeah its the join method on PlayerActivity
> > 
> > 
> > Like make them more like resume where they did the link thingy
> 
> Yeah I was doing this originally I was just thinking that people would want a location for people verifying but yeah that makes more sense in the end. Atm in about to board a plane but I'll fix it asap when im back

I think i can help with that too, will pr if i have time.


lol : riky sama is rich ...

**Comment by JSH32** [comment]
#7 Fixed this
